### ISSUE TITLE
ERROR:  rpc error: code = Unknown desc = LOGIN failed, for Office365 accounts.

### ISSUE THREAD

**Issue by rinshadka** [turbot/steampipe-plugin-imap#23]
**Describe the bug**
Getting below error in DBeaver while accessing the tables inside imap schema,
```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [HV000]: ERROR: rpc error: code = Unknown desc = LOGIN failed.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:187)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:189)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5096)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: rpc error: code = Unknown desc = LOGIN failed.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 7 more
```

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.6

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/imap@latest | 0.4.0  

**To reproduce**
Add O365 imap settings in config/imap.spc file. start the steampipe in service mode. Access the tables under imap schema.

**Expected behavior**
Get imap_mailbox and imap_message table content visible while using O365 account, just like its working if added bluehost imap account.

**Additional context**
It was working fine with the bluehost IMAP account. Just migrated the mail to o365 and facing this issue now. sample imap.spc file below:

```
connection "imap" {
  plugin = "imap"
  port = 993
  host = "outlook.office365.com"
  login = "user@domain.com"
  password = "xxxxxxxxxx"
```
This account is not having any 2FA configured. So for 0365 accounts, do we need to have any other settings at the account side like setting up App password ?

Thanks.

**Comment by graza-io** [comment]
@rinshadka would you be able to test using Steampipe directly using `steampipe query "select * from imap_message limit 10;"` from your terminal (assuming this is a local setup).

If you still encounter an issue here, would you be able to send over some censored logs - you can find them in `~/.steampipe/logs`. This may help us to locate and debug any issues in the plugin.

**Comment by rinshadka** [comment]
Thanks @graza-io for the response, below is the response from steampipe query:

**steampipe query "select * from imap_message limit 10;"**
 ```
Error: LOGIN failed. (SQLSTATE HV000)

+-----------+------------+---------+------------+--------------+--------------+---------------+---------+------+-------------+-----------+-----------+----------------+--------+-------+----------------+---------+-------------+---------+-------+------+
| timestamp | from_email | subject | message_id | to_addresses | cc_addresses | bcc_addresses | seq_num | size | attachments | body_html | body_text | embedded_files | errors | flags | from_addresses | headers | in_reply_to | mailbox | query | _ctx |
+-----------+------------+---------+------------+--------------+--------------+---------------+---------+------+-------------+-----------+-----------+----------------+--------+-------+----------------+---------+-------------+---------+-------+------+
+-----------+------------+---------+------------+--------------+--------------+---------------+---------+------+-------------+-----------+-----------+----------------+--------+-------+----------------+---------+-------------+---------+-------+------+
```

**less database-2023-07-28.log**

```
2023-07-28 14:25:36.562 UTC [3004739] LOG:  connection received: host=127.0.0.1 port=50850
2023-07-28 14:25:36.570 UTC [3004739] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_d392 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-07-28 14:25:42.389 UTC [WARN]  hub: stream receive error rpc error: code = Unknown desc = LOGIN failed. (0xc0006ea300)
2023-07-28 14:25:42.389 UTC [3004739] ERROR:  rpc error: code = Unknown desc = LOGIN failed.
2023-07-28 14:25:42.389 UTC [3004739] STATEMENT:  select * from imap_message limit 10;
2023-07-28 14:25:42.390 UTC [3004739] LOG:  disconnection: session time: 0:00:05.828 user=steampipe database=steampipe host=127.0.0.1 port=50850
```

**less plugin-2023-07-26.log**

```
2023-07-28 14:25:42.389 UTC [ERROR] steampipe-plugin-imap.plugin: [ERROR] 1690554336790: connection_error: host=outlook.office365.com port=993 hostPort=outlook.office365.com:993 tlsEnabled=true login=xxxx@xxxxx.com err="LOGIN failed."
2023-07-28 14:25:42.389 UTC [WARN]  steampipe-plugin-imap.plugin: [WARN]  1690554336790: doList callHydrateWithRetries (xxxxx-1690554336790) returned err LOGIN failed.
2023-07-28 14:25:42.389 UTC [WARN]  steampipe-plugin-imap.plugin: [WARN]  1690554336790: QueryData StreamError LOGIN failed. (xxxx-1690554336790)
2023-07-28 14:25:42.389 UTC [WARN]  steampipe-plugin-imap.plugin: [WARN]  1690554336790: streamRows for xxxx-1690554336790 - execution has failed (LOGIN failed.) - calling queryCache.AbortSet
2023-07-28 14:25:42.389 UTC [WARN]  steampipe-plugin-imap.plugin: [WARN]  1690554336790: executeForConnection xxxx returned error LOGIN failed.
2023-07-28 14:25:42.389 UTC [WARN]  steampipe-plugin-imap.plugin: [WARN]  1690554336790: error channel received LOGIN failed.
```
**~/.steampipe$ cat config/imap.spc**

```
connection "xxxx" {
  plugin = "imap"
  port = 993
  host = "outlook.office365.com"
  login = "xxxx@xxxx"
  password = "xxxxxxxx"
  }
```

**telnet outlook.office365.com 993**
```
Trying 2603:1026:c0d:c2d::2...
Connected to ooc-g2.tm-4.office.com.
Escape character is '^]'.
```

Thanks.

**Comment by graza-io** [comment]
Thanks @rinshadka - very detailed response!

Unfortunately I am unable to replicate this issue, I don't really use my 365 account (hence no mail messages) but you can see I was able to login and query successfully from the mailbox listing.

![imap](https://github.com/turbot/steampipe-plugin-imap/assets/53316123/9cba9e46-7836-4dfd-ab3f-1ddbc9159cd4)

Not really sure where to direct you next, I assume you've checked the credentials against actively logging into the web app, you mentioned no 2fa.

@misraved do you have any suggestions?

**Comment by graza-io** [comment]
Additional context, I am able to replicate the error if I deliberately set incorrect credentials:
![imap2](https://github.com/turbot/steampipe-plugin-imap/assets/53316123/0d821be7-2742-4fd9-8841-ac7b264b94a8)

**Comment by rinshadka** [comment]
Thanks @graza-io, I was able to work with IMAP plugin earlier while I was using my bluehost email provider. But once I switched to O365 , then started this issue.

In Parallel I have tried configuring the same in thunderbird email client and able to successfully login. ( An extra login prompt will come from Microsoft website in a small window) 

![image](https://github.com/turbot/steampipe-plugin-imap/assets/40381766/274cea31-b775-448f-b507-1c01decb2759)

Whenever I change the Authentication Method from "OAuth2" to "Normal Password" , it will break.

Thanks

**Comment by graza-io** [comment]
Ok, this looks like we don't currently have support for OAuth2 in this plugin.

This is something we will look at implementing in the near future.

Adding reference note: https://github.com/emersion/go-imap/issues/487

**Comment by chikkujimmy** [comment]
Just following up with this issue, we tried creating a free user email under outlook.com and created an app password by enabling 2FA following [these](https://support.microsoft.com/en-us/account-billing/create-app-passwords-from-the-security-info-preview-page-d8bc744a-ce3f-4d4d-89c9-eb38ab9d4137) instructions and it worked but when we are using o365 with app password the issue persists. Would you be able to provide any details on why this could be happening?
